<a href="https://colab.research.google.com/github/SIDDHAY19/Python/blob/main/EXP11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array: ")
print(arr1d)

1D Array: 
[1 2 3 4 5]


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("\n2D Array: ")
print(arr2d)


2D Array: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("\n3D Array: ")
print(arr3d)


3D Array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print("\nAddition of 1D and 1D array:")
arr_sum = np.array([1, 2, 3]) + np.array([3, 2, 1])
print(arr_sum)

print("\nConcatenation of 1D array with itself:")
print(np.concatenate([arr1d, arr1d]))

print("\nMultiplication of 2D array with a 2D array:")
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.dot(arr1, arr2))

print("\nSum of the first 2D array of 3D array:")
print(arr3d[0, ...].sum())


Addition of 1D and 1D array:
[4 4 4]

Concatenation of 1D array with itself:
[1 2 3 4 5 1 2 3 4 5]

Multiplication of 2D array with a 2D array:
[[19 22]
 [43 50]]

Sum of the first 2D array of 3D array:
21
